### ISSUE TITLE
testのbuild.shがコケる

### ISSUE THREAD

**Issue by yyoshiaki** [pitagora-network/DAT2-cwl#14]
https://github.com/pitagora-network/DAT2-cwl/blob/master/test/tool/test#L54

ですが、Dockerfileからbuildする必要がある場合、

https://github.com/pitagora-network/DAT2-cwl/blob/master/tool/fastqc/build.sh#L4

を真似て書くと、相対パスがずれてbuildできません。例えば

```bash
  # build_file=${tool_dir}/build.sh
  # bash ${build_file}
  cd ${tool_dir}
  bash build.sh
  cd -
```

で解決します。良ければPRしますがいかがでしょう？

**Comment by inutano** [comment]
よさそう、 @suecharo いかがかしら

**Comment by tom-tan** [comment]
#12 にこの Issue 用の修正が含まれています。

**Comment by inutano** [comment]
#12 をマージしたので `test` については解決しましたが、 `all_test` で同じ問題が起きるのでそちらを解決する PR を #23 で投げてます。

**Comment by inutano** [comment]
問題は `test/workflow/test` では Dockerfile のビルドをやらないので、コケてしまう…。 Workflow の中で呼んでいるツールを個別に調べて Dockerfile があれば build.sh を実行する、とすれば解決できるけど、ちょっと面倒だな…と思って放置してしまっている。先に tool を全部テストしていればコンテナがキャッシュされるので問題は起きないので、開発時にちょっと気付きにくい。

ふつう Workflow のテストする前に tool のテストするでしょ、といえばそうなんだけど…。

**Comment by suecharo** [comment]
修正します。

**Comment by inutano** [comment]
このtest時のコンテナのビルドの件、test時にちゃんとビルドされたとしても、実際に使う際に個別環境ごとにビルドする必要が出てきてしまうので、 `dockerFile: Dockerfile` としてツール実行時にランナーがビルドするようにしてしまったほうがよさそうです。（ほんとは Dockerhub なり quay.io なりでホストするのがいいけど、そこまでするか？みたいなものもあるので）なので、現在 `develop` にマージされているものはそのように修正しておきます。このissueも一旦閉じておきますね。

**Comment by inutano** [comment]
…と思ったら

```
requirements:
  DockerRequirement:
    dockerFile: <location of dockerfile>
```

としてもファイルからビルドしてくれるわけではなかったのであった 😇

**Comment by inutano** [comment]
というわけでわざわざhubでホストするほどでもないというものに関しては `dockerFile` の中に直接 `Dockerfile` の中身を書いてしまうという作戦でいきます。

**Comment by inutano** [comment]
そして最終的にこれ https://github.com/common-workflow-language/cwltool/issues/312 にぶちあたりました。`ADD` や `COPY` をするならやはり事前にビルドするしかないのか…つらい…………

**Comment by inutano** [comment]
そうすると今回作ったCWLを実行するためには、まず test を走らせてコンテナをビルドしてからでないと動きません、てなってしまいますね `configure` みたいなスクリプトを作っておいて初回にこれ実行してローカルにコンテナをビルドしておいてね、とするくらいが妥当でしょうか。

**Comment by tom-tan** [comment]
今だと GHCR にコンテナイメージを置く方法も検討の余地がありそうですが、どうしましょうか？

**Comment by inutano** [comment]
中長期での保証を考えてもイメージをGHCRにホストするほうがよさそうですね

**Comment by suecharo** [comment]
release 1.1.0 でここらへんを修正したので close します。
